#language: cpp
#os:
#  - linux
#compiler:
#  - gcc
#script:
#  - g++ main.cpp -std=c++11
#  - ./a.out
#after_success:
# bash <(curl -s https://codecov.io/bash) 

language: cpp
os:
    - linux
    - osx
compiler:
    - gcc
matrix:
script:
    # скрипт сборки и тестирования проекта:
  - g++ main.cpp -std=c++11
  - ./a.out
  - ctest --output-on-failure
